-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-22 21:54:35 BST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

-- Student Name:    Thamsanqa Sibanda
-- Student Number:  C18727971
-- Date:            22 April 2020
-- Question:        ERD Create SQL with drop tables

DROP TABLE hh_adtype CASCADE CONSTRAINTS;

DROP TABLE hh_adverts CASCADE CONSTRAINTS;

DROP TABLE hh_agent CASCADE CONSTRAINTS;

DROP TABLE hh_branch CASCADE CONSTRAINTS;

DROP TABLE hh_clients CASCADE CONSTRAINTS;

DROP TABLE hh_procat CASCADE CONSTRAINTS;

DROP TABLE hh_property CASCADE CONSTRAINTS;

DROP TABLE hh_protype CASCADE CONSTRAINTS;

DROP TABLE p_forsale CASCADE CONSTRAINTS;

DROP TABLE valu_app CASCADE CONSTRAINTS;

CREATE TABLE hh_adtype (
    adtypeid  NUMBER(7) NOT NULL,
    adtype    VARCHAR2(40 CHAR)
);

ALTER TABLE hh_adtype ADD CONSTRAINT ad_type_pk PRIMARY KEY ( adtypeid );

CREATE TABLE hh_adverts (
    addate    DATE NOT NULL,
    adcost    NUMBER(9, 2) NOT NULL,
    pid       NUMBER(7) NOT NULL,
    adtypeid  NUMBER(7) NOT NULL
);

ALTER TABLE hh_adverts
    ADD CONSTRAINT adverts_pk PRIMARY KEY ( pid,
                                            adcost,
                                            addate );

CREATE TABLE hh_agent (
    agentid      NUMBER(7) NOT NULL,
    aname        VARCHAR2(40 CHAR) NOT NULL,
    basicsalary  NUMBER(9, 2),
    bid          NUMBER(7) NOT NULL
);

ALTER TABLE hh_agent ADD CONSTRAINT agent_pk PRIMARY KEY ( agentid );

CREATE TABLE hh_branch (
    bid    NUMBER(7) NOT NULL,
    bname  VARCHAR2(40 CHAR) NOT NULL,
    baddr  VARCHAR2(80)
);

ALTER TABLE hh_branch ADD CONSTRAINT branch_pk PRIMARY KEY ( bid );

CREATE TABLE hh_clients (
    cid      NUMBER(7) NOT NULL,
    cname    VARCHAR2(40 CHAR) NOT NULL,
    caddr    VARCHAR2(80) NOT NULL,
    cphone   VARCHAR2(13),
    cemail   VARCHAR2(50),
    cbudget  NUMBER(9, 2)
);

ALTER TABLE hh_clients ADD CONSTRAINT hh_clients_pk PRIMARY KEY ( cid );

CREATE TABLE hh_procat (
    catid    NUMBER(7) NOT NULL,
    catname  VARCHAR2(40 CHAR) NOT NULL
);

ALTER TABLE hh_procat ADD CONSTRAINT pro_cat_pk PRIMARY KEY ( catid );

CREATE TABLE hh_property (
    pid          NUMBER(7) NOT NULL,
    paddr        VARCHAR2(80) NOT NULL,
    no_beds      NUMBER(8),
    salemethod   VARCHAR2(255 CHAR),
    regdate      DATE NOT NULL,
    notes        VARCHAR2(255),
    minaskprice  NUMBER(9, 2),
    valu         NUMBER(9, 2),
    agentid      NUMBER(7) NOT NULL,
    protypeid    NUMBER(7) NOT NULL
);

ALTER TABLE hh_property ADD CONSTRAINT property_pk PRIMARY KEY ( pid );

CREATE TABLE hh_protype (
    protypeid    NUMBER(7) NOT NULL,
    protypename  VARCHAR2(40 CHAR) NOT NULL,
    catid        NUMBER(7) NOT NULL
);

ALTER TABLE hh_protype ADD CONSTRAINT pro_type_pk PRIMARY KEY ( protypeid );

CREATE TABLE p_forsale (
    forsaleid   NUMBER(7) NOT NULL,
    saleprice   NUMBER(9, 2),
    salestatus  VARCHAR2(10) NOT NULL,
    commission  NUMBER(9, 2),
    pid         NUMBER(7) NOT NULL,
    sellerid    NUMBER(7) NOT NULL,
    buyerid     NUMBER(7)
);

ALTER TABLE p_forsale
    ADD CHECK ( salestatus IN (
        'For Sale',
        'Sold'
    ) );

ALTER TABLE p_forsale ADD CONSTRAINT p_forsale_pk PRIMARY KEY ( forsaleid );

CREATE TABLE valu_app (
    appdate  DATE NOT NULL,
    pid      NUMBER(7) NOT NULL
);

ALTER TABLE valu_app ADD CONSTRAINT valu_app_pk PRIMARY KEY ( pid,
                                                              appdate );

ALTER TABLE hh_adverts
    ADD CONSTRAINT adverts_ad_type_fk FOREIGN KEY ( adtypeid )
        REFERENCES hh_adtype ( adtypeid );

ALTER TABLE hh_adverts
    ADD CONSTRAINT adverts_property_fk FOREIGN KEY ( pid )
        REFERENCES hh_property ( pid );

ALTER TABLE hh_agent
    ADD CONSTRAINT agent_branch_fk FOREIGN KEY ( bid )
        REFERENCES hh_branch ( bid );

ALTER TABLE p_forsale
    ADD CONSTRAINT buyer FOREIGN KEY ( buyerid )
        REFERENCES hh_clients ( cid );

ALTER TABLE p_forsale
    ADD CONSTRAINT pid FOREIGN KEY ( pid )
        REFERENCES hh_property ( pid );

ALTER TABLE hh_protype
    ADD CONSTRAINT pro_type_pro_cat_fk FOREIGN KEY ( catid )
        REFERENCES hh_procat ( catid );

ALTER TABLE hh_property
    ADD CONSTRAINT property_agent_fk FOREIGN KEY ( agentid )
        REFERENCES hh_agent ( agentid );

ALTER TABLE hh_property
    ADD CONSTRAINT property_pro_type_fk FOREIGN KEY ( protypeid )
        REFERENCES hh_protype ( protypeid );

ALTER TABLE p_forsale
    ADD CONSTRAINT seller FOREIGN KEY ( sellerid )
        REFERENCES hh_clients ( cid );

ALTER TABLE valu_app
    ADD CONSTRAINT valu_app_property_fk FOREIGN KEY ( pid )
        REFERENCES hh_property ( pid );

COMMIT;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
